<?php

namespace Database\Seeders;

use App\Models\Kelas;
use App\Models\Siswa;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class SiswaNewSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // kelas 3
            [
                'name' => 'Muhammad Ridho',
                'nisn' => '3150074890',
                'jk' => 'Laki-laki',
                'tmpt_lahir' => 'Samarinda',
                'tgl_lahir' => '2015-10-18',
                'agama' => 'Islam',
                'nama_ayah' => 'Nur Rahmad',
                'nama_ibu' => 'Normiati',
                'pendidikan_ayah' => 'SMA / sederajat',
                'pendidikan_ibu' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'Wiraswasta',
                'rt' => '4',
                'rw' => '0',
                'provinsi_id' => '64',
                'kabupaten_id' => '6472',
                'kecamatan_id' => 'Kec. Samarinda Seberang',
                'kelurahan_id' => 'Sungai Keledang',
                'jenis_tinggal' => 'Bersama orang tua',
                'nama_jalan' => 'Jl. Hj. Jahrah',
                'no_hp' => '082350254600',
                'spp' => 450000,
                'dpp' => 4000000,
                'seragam' => 1450000,
                'kelas' => 'Kelas 3',
                'category_kelas' => 'CORDOBA',
            ],
            // kelas 4
            [
                'name' => 'Muhammad Ridho',
                'nisn' => '3141087342',
                'jk' => 'Laki-laki',
                'tmpt_lahir' => 'Samarinda',
                'tgl_lahir' => '2014-11-14',
                'agama' => 'Islam',
                'nama_ayah' => 'Bambang Sutikno',
                'nama_ibu' => 'Masrifah',
                'pendidikan_ayah' => 'SMP / sederajat',
                'pendidikan_ibu' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'rt' => '7',
                'rw' => '0',
                'provinsi_id' => '64',
                'kabupaten_id' => '6472',
                'kecamatan_id' => 'Kec. Samarinda Seberang',
                'kelurahan_id' => 'Sungai Keledang',
                'jenis_tinggal' => 'Bersama orang tua',
                'nama_jalan' => 'Jl. Hj. Jahrah',
                'no_hp' => '085841979361',
                'spp' => 300000,
                'dpp' => 0,
                'seragam' => 1450000,
                'kelas' => 'Kelas 4',
                'category_kelas' => 'AMMAN',
            ],
            // kelas 4
            [
                'name' => 'Muhammad Abidzar Al Ghifari',
                'nisn' => '3145475918',
                'jk' => 'Laki-laki',
                'tmpt_lahir' => 'Tanrutedong',
                'tgl_lahir' => '2014-08-19',
                'agama' => 'Islam',
                'nama_ayah' => 'INDO ENRE',
                'nama_ibu' => 'SMP / sederajat',
                'pendidikan_ayah' => 'D3',
                'pendidikan_ibu' => 'Wiraswasta',
                'pekerjaan_ayah' => 'Tidak bekerja',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'rt' => '25',
                'rw' => '0',
                'provinsi_id' => '64',
                'kabupaten_id' => '6472',
                'kecamatan_id' => 'Kec. Loa Janan Ilir',
                'kelurahan_id' => 'Rapak Dalam',
                'jenis_tinggal' => 'Bersama orang tua',
                'nama_jalan' => 'Jl. KH. Harun Nafsi',
                'no_hp' => '082192896443',
                'spp' => 100000,
                'dpp' => 4000000,
                'seragam' => 1450000,
                'kelas' => 'Kelas 4',
                'category_kelas' => 'BUKHARA',
            ],
            // kelas 1
            [
                'name' => 'Muhammad Abizar Al Ghifari',
                'nisn' => '3175197397',
                'jk' => 'Laki-laki',
                'tmpt_lahir' => 'Samarinda',
                'tgl_lahir' => '2017-07-02',
                'agama' => 'Islam',
                'nama_ayah' => 'Hamidin',
                'nama_ibu' => 'Noor Huda',
                'pendidikan_ayah' => 'D3',
                'pendidikan_ibu' => 'D3',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'rt' => '0',
                'rw' => '0',
                'provinsi_id' => '64',
                'kabupaten_id' => '6472',
                'kecamatan_id' => 'Kec. Samarinda Seberang',
                'kelurahan_id' => 'Sungai Keledang',
                'jenis_tinggal' => 'Bersama orang tua',
                'nama_jalan' => 'Jl. Bung Tomo Gang Surya Indah 9 No. 4C',
                'no_hp' => '085250936271',
                'spp' => 400000,
                'dpp' => 3000000,
                'seragam' => 1450000,
                'kelas' => 'Kelas 1',
                'category_kelas' => 'INSTANBUL',
            ],
            // kelas 1
            [
                'name' => 'MUHAMMAD ABIZAR AL-GHIFARI',
                'nisn' => '3169735906',
                'jk' => 'Laki-laki',
                'tmpt_lahir' => 'SAMARINDA',
                'tgl_lahir' => '2016-09-23',
                'agama' => 'Islam',
                'nama_ayah' => 'RUSMAN',
                'nama_ibu' => 'MULIATI',
                'pendidikan_ayah' => 'SMP / sederajat',
                'pendidikan_ibu' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'rt' => '1',
                'rw' => '0',
                'provinsi_id' => '64',
                'kabupaten_id' => '6472',
                'kecamatan_id' => 'Kec. Samarinda Seberang',
                'kelurahan_id' => 'Baqa',
                'jenis_tinggal' => 'Bersama orang tua',
                'nama_jalan' => 'JALAN PADAT KARYA, NO. 47',
                'no_hp' => '081346313035',
                'spp' => 450000,
                'dpp' => 4000000,
                'seragam' => 1450000,
                'kelas' => 'Kelas 2',
                'category_kelas' => "YERUSSALEM",
            ],
            [
                'name' => 'Rafa Nauval Gautama',
                'nisn' => '0147303500',
                'jk' => 'Laki-laki',
                'tmpt_lahir' => 'Samarinda',
                'tgl_lahir' => '2014-04-14',
                'agama' => 'Islam',
                'asal_sekolah' => 'Rasyiqah',
                'tgl_masuk_sekolah' => '2025-01-22',
                'kelas' => 'Kelas 4',
                'category_kelas' => 'BUKHARA',
                'nama_ayah' => 'Iqbal Gautama',
                'nama_ibu' => 'Sita Munawarah',
                'pendidikan_ayah' => 'S1',
                'pendidikan_ibu' => 'D3',
                'pekerjaan_ayah' => 'BUMN',
                'pekerjaan_ibu' => 'Ibu Rumah tangga',
                'nama_jalan' => 'Jln pattimura Blok V No 52 Samarinda Seberang',
                'provinsi_id' => '64',
                'kabupaten_id' => 'Kota Samarinda',
                'kecamatan_id' => 'Loa Janan Ilir',
                'kelurahan_id' => 'mangkupalas',
                'jenis_tinggal' => 'Bersama orang tua',
                'rw' => '03',
                'spp'=> 400000,
                'dpp' => 4000000,
                'seragam' => 1450000,
                'rt' => '09',
                'rw' => '00',
                'no_hp' => '085250060439',
            ],
            [
                'name' => 'Awra Tsabita Humairah Jalil',
                'nisn' => '0146087227',
                'jk' => 'Perempuan',
                'tmpt_lahir' => 'Bontang',
                'tgl_lahir' => '2014-03-29',
                'agama' => 'Islam',
                'asal_sekolah' => 'Islam Bunayya Samarinda',
                'tgl_masuk_sekolah' => '',
                'kelas' => 'Kelas 5',
                'category_kelas' => 'AL-QUDS',
                'nama_ayah' => 'Awaluddin Jalil',
                'nama_ibu' => 'Taqdiraa',
                'pendidikan_ayah' => 'Diploma 3',
                'pendidikan_ibu' => 'S1',
                'pekerjaan_ayah' => 'Jurnalis',
                'pekerjaan_ibu' => 'Guru',
                'nama_jalan' => 'Perumahan Tamansari Grand Samarinda, Clusterk Kakaban H12/9',
                'provinsi_id' => '64',
                'kabupaten_id' => 'Kota Samarinda',
                'kecamatan_id' => 'Loa Janan Ilir',
                'kelurahan_id' => 'Harapan Baru',
                'jenis_tinggal' => 'Bersama orang tua',
                'rt' => '43',
                'rw' => '00',
                'spp' => 175000,
                'dpp' => 4000000,
                'seragam' => 1650000,
                'no_hp' => '081134500616',
            ],
            [
                'name' => 'Alzea Adrena Saya',
                'nisn' => '3168882847',
                'jk' => 'Perempuan',
                'tmpt_lahir' => 'Samarinda',
                'tgl_lahir' => '2016-04-23',
                'agama' => 'Islam',
                'asal_sekolah' => 'Null',
                'tgl_masuk_sekolah' => 'Null',
                'kelas' => 'Kelas 2',
                'category_kelas' => 'KAIRO',
                'nama_ayah' => 'Null',
                'nama_ibu' => 'Null',
                'pendidikan_ayah' => 'Null',
                'pendidikan_ibu' => 'Null',
                'pekerjaan_ayah' => 'Null',
                'pekerjaan_ibu' => 'Null',
                'nama_jalan' => 'NUll',
                'provinsi_id' => '64',
                'kabupaten_id' => 'Kota Samarinda',
                'kecamatan_id' => 'Samarinda Seberang',
                'kelurahan_id' => 'Bungtomo',
                'jenis_tinggal' => 'Bersama orang tua',
                'rt' => '',
                'rw' => '00',
                'spp' => 0,
                'dpp' => 0,
                'seragam' => 1650000,
                'no_hp' => '081134500616',
            ],
        ];

        foreach ($data as $siswa_data) {
            $siswa = Siswa::create([
                'id' => Str::uuid(),
                'name' => $siswa_data['name'],
                'nisn' => $siswa_data['nisn'],
                'jk' => $siswa_data['jk'],
                'tmpt_lahir' => $siswa_data['tmpt_lahir'],
                'tgl_lahir' => $siswa_data['tgl_lahir'],
                'agama' => $siswa_data['agama'],
                'spp' => $siswa_data['spp'],
                'dpp' => $siswa_data['dpp'],
                'seragam' => $siswa_data['seragam'],
                'va_number' => null,
                'nama_pendidikan' => null,
                'nama_jalan_pendidikan' => null,
                'kelas_tahun' => $siswa_data['kelas_tahun'] ?? null,
                'tanggal_masuk' => null,
                'beasiswa' => null,
                'foto' => asset('asset_dashboard/img/default.jpg'),
                'select_data' => 'orang_tua',
                'nama_ayah' => $siswa_data['nama_ayah'],
                'nama_ibu' => $siswa_data['nama_ibu'],
                'pendidikan_ayah' => $siswa_data['pendidikan_ayah'],
                'pendidikan_ibu' => $siswa_data['pendidikan_ibu'],
                'pekerjaan_ayah' => $siswa_data['pekerjaan_ayah'],
                'pekerjaan_ibu' => $siswa_data['pekerjaan_ibu'],
                'nama_wali' => null,
                'pekerjaan_wali' => null,
                'alamat_wali' => null,
                'rt' => $siswa_data['rt'],
                'rw' => $siswa_data['rw'],
                'provinsi_id' => $siswa_data['provinsi_id'],
                'kabupaten_id' => $siswa_data['kabupaten_id'],
                'kecamatan_id' => $siswa_data['kecamatan_id'],
                'kelurahan_id' => $siswa_data['kelurahan_id'],
                'jenis_tinggal' => $siswa_data['jenis_tinggal'],
                'nama_jalan' => $siswa_data['nama_jalan'],
                'no_hp' => $siswa_data['no_hp'],
                'slug' => Str::slug($siswa_data['name'] . '-' . Str::random(5)),
            ]);

            $kelas = Kelas::where('name', $siswa_data['kelas'])->first();
            if ($kelas) {
                $siswa->kelas()->sync([
                    $kelas->id => ['category_kelas' => $siswa_data['category_kelas']],
                ]);
            } else {
                echo "❌ Kelas tidak ditemukan: {$siswa_data['kelas']}\n";
            }
        }
    }
}
